"use strict";
exports.__esModule = true;
var message = 'Hello World';
console.log(message);
var x = 10;
var y = 20;
var sum;
var title = 'Codevolution';
var isBeginner = true;
var total = 0;
var name = 'Your Name';
var sentence = "My Name is " + name + "\nI am a beginner in Typescript";
console.log(sentence);
